feature_requests/auth.py
import functools

from flask import Blueprint, flash, g, redirect, render_template, request, session, url_for
from werkzeug.security import check_password_hash, generate_password_hash

from .models import db, User

bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/register', methods=('GET', 'POST'))
def register():
    if request.method == 'POST':
        username = request.form['username']
        email = request.form['email']
        password = request.form['password']
        error = None

        if not username:
            error = 'Username is required.'
        elif not email:
            error = 'Email is required.'
        elif not password:
            error = 'Password is required.'
        elif User.query.filter_by(username=username).first() is not None:
            error = 'Username {} already registered.'.format(username)

        if error is None:
            user = User(username=username, email=email, password=generate_password_hash(password))
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('auth.login'))

        flash(error)

    return render_template('auth/register.html')


@bp.route('/login', methods=('GET', 'POST'))
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        error = None
        user = User.query.filter_by(username=username).first()

        if user and check_password_hash(user.password, password):
            session.clear()
            session['user_id'] = user.id
            return redirect(url_for('index'))
        else:
            error = 'Incorrect username/password.'
            flash(error)

    return render_template('auth/login.html')


@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = User.query.filter_by(id=user_id)


@bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('auth.login'))


def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))

        return view(**kwargs)

    return wrapped_view

feature_requests/views.py
from datetime import datetime

from flask import Blueprint, flash, render_template, request
from sqlalchemy import and_

from .models import db, FeatureRequest, Customer, Priority, ProductArea
from .auth import login_required


bp = Blueprint('features', __name__)


@bp.route('/', methods=['GET'])
@login_required
def index():
    feature_requests = FeatureRequest.query.filter(FeatureRequest.closed == False).all()
    return render_template('index.html', feature_requests=feature_requests)


@bp.route('/create',  methods=('GET', 'POST'))
@login_required
def create():
    db.create_all()
    if request.method == 'POST':
        title = request.form['title']
        description = request.form['description']
        customer_id = request.form['customer_id']
        priority_id = request.form['priority_id']
        product_area = request.form['product_area']
        target_date = request.form['target_date']

        # convert target date to datetime object.
        targetdate = datetime.strptime(target_date, '%m/%d/%Y %H:%M %p')

        error = None

        if not title:
            error = 'Title is required.'
        elif not description:
            error = 'Description is required.'
        elif not customer_id:
            error = 'Client ID is required.'
        elif not priority_id:
            error = 'Priority is required.'
        elif not product_area:
            error = 'Product area is required.'
        elif not target_date:
            error = 'Target date is required.'
        elif targetdate < datetime.utcnow() or targetdate == datetime.utcnow():
            error = 'Target date should be in the future.'
        elif FeatureRequest.query.filter(and_(FeatureRequest.customer_id == customer_id,
                                              FeatureRequest.priority_id == priority_id,
                                              FeatureRequest.closed == False)).all():
            error = 'Customer already has feature request with same priority. Please assign another priority.'

        flash(error)

        if error is None:
            feature_request = FeatureRequest(title=title, description=description, customer_id=customer_id,
                                             priority_id=priority_id, product_area_id=product_area,
                                             target_date=targetdate)
            db.session.add(feature_request)
            db.session.commit()
            flash('Feature request added successfully.')

    clients = Customer.query.all()
    priority_list = Priority.query.all()
    product_areas = ProductArea.query.all()

    return render_template('create.html', clients=clients, priority_list=priority_list, product_areas=product_areas)


@bp.route('/add_client', methods=['GET', 'POST'])
@login_required
def add_client():
    if request.method == 'POST':
        name = request.form['name']
        error = None

        if not name:
            error = 'Client name is required.'
            flash(error)

        if error is None:
            client_name = Customer(name=name)
            db.session.add(client_name)
            db.session.commit()
            flash('Client added successfully.')

    return render_template('client.html')


@bp.route('/add_priority', methods=['GET', 'POST'])
@login_required
def add_priority():
    if request.method == 'POST':
        priority_level = request.form['priority_level']
        error = None

        if not priority_level:
            error = 'Priority level is required.'
            flash(error)

        if error is None:
            priority = Priority(priority_level=priority_level)
            db.session.add(priority)
            db.session.commit()
            flash('Priority added successfully.')

    return render_template('priority.html')


@bp.route('/add_product_area', methods=['GET', 'POST'])
@login_required
def add_product_area():
    if request.method == 'POST':
        name = request.form['name']
        error = None

        if not name:
            error = 'Product area is required.'
            flash(error)

        if error is None:
            product_area = ProductArea(name=name)
            db.session.add(product_area)
            db.session.commit()
            flash('Product area added successfully.')

    return render_template('product_area.html')

feature_requests/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %} - IWS Feature Requests</title>
    <!-- Static files -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-datetimepicker.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='font-awesome/css/fontawesome.min.css') }}">
</head>
<body>
    <div>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
            <a class="navbar-brand" href="{{ url_for('index') }}">IWS Feature Requests</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                {% if g.user %}
                    <li class="nav-item active"><a class="nav-link" href="{{ url_for('index') }}">Home
                        <span class="sr-only">(current)</span></a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('features.create') }}">New Feature Request</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('features.add_client') }}">New Client</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('features.add_priority') }}">New Priority</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('features.add_product_area') }}">New Product Area</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.logout') }}">Log Out
                        <i class="fa fa-power"></i></a></li>
                    <li class="nav-item"><span class="navbar-text">{{ g.user.username }}</span></li>

                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.register') }}">Register</a></li>
                    <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.login') }}">Log In</a></li>
                {% endif %}
                </ul>
            </div>
        </nav>

        <!-- Content -->
        <section class="content">
            <header>
                {% block header %}{% endblock %}
            </header>

            {% for message in get_flashed_messages() %}
                <div class="flash">{{ message }}</div>
            {% endfor %}

            {% block content %}

            {% endblock %}
        </section>

        <!--Footer-->
        <footer class="py-5" style="background-color: #e3f2fd;">
            <div>
                <p align="center">Copyright &copy; Anna Makarudze 2018</p>
            </div>
        </footer>

    </div>

    <script type=text/javascript src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script type=text/javascript src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
    <script type=text/javascript src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script type=text/javascript src="{{ url_for('static', filename='js/moment.min.js') }}"></script>
    <script type=text/javascript src="{{ url_for('static', filename='font-awesome/fontawesome.min.js') }}"></script>
    <script type=text/javascript src="{{ url_for('static', filename='js/bootstrap-datetimepicker.min.js') }}"></script>

     <script>
         $(function () {
              $('#target_date').datetimepicker();
         });
     </script>
</body>
</html>

feature_requests/templates/client.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Add Client{% endblock %}</h1>
{% endblock %}

{% block content %}
    <form method="post">
        <div class="form-group row">
            <label for="name" class="col-sm-2 col-form-label">Client Name</label>
            <div class="col-sm-10">
                <input class="form-control" name="name" id="name" placeholder="Enter Client Name" required>
            </div>
        </div>
        <input type="submit" class="btn btn-primary" value="Add">
    </form>
{% endblock %}

feature_requests/templates/create.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Add New Feature Request{% endblock %}</h1>
{% endblock %}

{% block content %}
    <form method="post">
        <div class="form-group row">
            <label for="title" class="col-sm-2 col-form-label">Title</label>
            <div class="col-sm-10">
                <input name="title" class="form-control" id="title" placeholder="Enter title" required>
            </div>
        </div>
        <div class="form-group row">
            <label for="description" class="col-sm-2 col-form-label">Description</label>
            <div class="col-sm-10">
                <textarea name="description" class="form-control" id="description" placeholder="Enter description"
                          rows="5" required>
                </textarea>
            </div>
        </div>
        <div class="form-group row">
            <label for="customer_id" class="col-sm-2 col-form-label">Customer</label>
            <div class="col-sm-10">
                <select name="customer_id" class="form-control" id="customer_id" placeholder="Select customer" required>
                    {% for client in clients %}
                        <option value="{{ client.id }}">{{ client['name'] }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="form-group row">
            <label for="priority_id" class="col-sm-2 col-form-label">Priority</label>
            <div class="col-sm-10">
                <select name="priority_id" class="form-control" id="priority_id"  placeholder="Select Priority"required>
                    {% for priority_level in priority_list %}
                        <option value="{{ priority_level.id }}">{{ priority_level['id'] }} - {{ priority_level['priority_level'] }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="form-group row">
            <label for="product_area" class="col-sm-2 col-form-label">Product Area</label>
            <div class="col-sm-10">
                <select name="product_area" class="form-control" id="product_area"  placeholder="Select Product Area"required>
                    {% for product_area in product_areas %}
                        <option value="{{ product_area.id }}">{{product_area['name'] }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="form-group row">
            <label for="target_date" class="col-sm-2 col-form-label">Target date</label>
            <div class="col-sm-10">
                <input name="target_date" class="form-control" id="target_date" placeholder="Enter target date" required>
            </div>
        </div>
        <input type="submit" class="btn btn-primary mb-2" value="Add">
    </form>

{% endblock %}

feature_requests/templates/feature_requests.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Feature Requests{% endblock %}</h1>
{% endblock %}

{% block content %}

{% endblock %}

feature_requests/templates/index.html
{% extends 'base.html' %}

{% block header %}

  <h1>{% block title %}Feature Requests{% endblock %}</h1>

{% endblock %}

{% block content %}
    {% if feature_requests %}
        <div class="row">
            <div class="col-sm-4"><b>Title</b></div>
            <div class="col-sm-2"><b>Client</b></div>
            <div class="col-sm-1"><b>Priority</b></div>
            <div class="col-sm-2"><b>Target Date</b></div>
            <div class="col-sm-2"><b>Date Created</b></div>
            <div class="col-sm-1"></div>
        </div>

        {% for feature_request in feature_requests %}
            <div class="row">
                <div class="col-sm-4">{{ feature_request['title'] }}</div>
                <div class="col-sm-2">{{ feature_request['customer_id'] }}</div>
                <div class="col-sm-1">{{ feature_request['priority_id'] }}</div>
                <div class="col-sm-2">{{ feature_request['target_date'] }}</div>
                <div class="col-sm-2">{{ feature_request['date_created'] }}</div>
                <div class="col-sm-1"><a class="btn btn-primary mb-2">Edit</a></div>
            </div>

        {% endfor %}

    {% else %}

        <p>No open feature requests to work on at this time.</p>

    {% endif %}

{% endblock %}

feature_requests/templates/priority.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Add Priority{% endblock %}</h1>
{% endblock %}

{% block content %}
    <form method="post">
        <div class="form-group row">
            <label for="priority_level" class="col-sm-2 col-form-label">Priority Level</label>
            <div class="col-sm-10">
                <input class="form-control" name="priority_level" id="priority_level" placeholder="Enter priority level" required>
            </div>
        </div>
        <input type="submit" class="btn btn-primary" value="Add">
    </form>
{% endblock %}

feature_requests/templates/product_area.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Add Product Area{% endblock %}</h1>
{% endblock %}

{% block content %}
    <form method="post">
        <div class="form-group row">
            <label for="name" class="col-sm-2 col-form-label">Product Area</label>
            <div class="col-sm-10">
                <input class="form-control" name="name" id="name" placeholder="Enter product area" required>
            </div>
        </div>
        <input type="submit" class="btn btn-primary" value="Add">
    </form>
{% endblock %}

feature_requests/templates/update.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}Edit "{{ feature['title'] }}"{% endblock %}</h1>
{% endblock %}

{% block content %}
  <form method="post">
       <div class="form-group row">
            <label for="title" class="col-sm-2 col-form-label">Title</label>
            <div class="col-sm-10">
                <input name="title" class="form-control" id="title"
                       value="{{ request.form['title'] or post['title'] }}" required>
            </div>
       </div>
      <div class="form-group row">
            <label for="description" class="col-sm-2 col-form-label">Description</label>
            <div class="col-sm-10">
                <textarea name="description" class="form-control" id="description" required>
                    {{ request.form['description'] or post['description'] }}
                </textarea>
            </div>
      </div>
      <div class="form-group row">
            <label for="client_id" class="col-sm-2 col-form-label">Client</label>
            <div class="col-sm-10">
                <input name="client_id" class="form-control" id="client_id"
                       value="{{ request.form['client_it'] or post['client_id'] }}" required>
            </div>
      </div>
      <div class="form-group row">
            <label for="priority_id" class="col-sm-2 col-form-label">Priority</label>
            <div class="col-sm-10">
                <select name="priority_id" class="form-control" id="priority_id" required>
                    {{ request.form['priority_id'] or post['priority'] }}"
                </select>
            </div>
      </div>
      <div class="form-group row">
            <label for="target_date" class="col-sm-2 col-form-label">Target date</label>
            <div class="col-sm-10">
                <input name="target_date" class="form-control" id="target_date" required>
                {{ request.form['target_date'] or post['target_date'] }}
            </div>
      </div>
      <div class="form-group row">
            <label for="closed" class="col-sm-2 col-form-label">Closed</label>
            <div class="col-sm-10">
                <input type="checkbox" name="closed" id="closed" value="{{ request.form['closed'] or post['closed'] }}">
            </div>
      </div>
    <input type="submit" class="btn-primary" value="Save">
  </form>
  <hr>
{% endblock %}